name: Build, Test and Deploy React Application
# Controls when the action will run.
on:
# Triggers the workflow on push or pull reuest events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - name: npm ci build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test
      # mets a jour la version du build avec le numéro de build construit à l'aide de l'id du worflow, du numéro d'écxecution et du nombre de tentatives
      - name: Set env
        run: |
          npm i -g semver
          echo "GITHUB_VERSION_BUILD=$(echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}))" >> $GITHUB_ENV
      - name: Update versionning
        run: |
          git config --global user.email "loise.fenoll@ynov.com"
          git config --global user.name "Loïse Fenoll"
          npm version ${{env.GITHUB_VERSION_BUILD}}
          echo ${{env.GITHUB_VERSION_BUILD}} >> README.md
          git commit -a -m "new version ${{env.GITHUB_VERSION_BUILD}}"
      - name: setup Pages
        id: Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build
          if-no-files-found: error
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build_tests
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
