name: Build, Test and Deploy React Application
# Controls when the action will run.
on:
# Triggers the workflow on push or pull reuest events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - name: npm ci build and test
        run: |
          npm ci
          npm run build --if-present
          npm test
      - name: setup Pages
        id: Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build
          if-no-files-found: error
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build_tests
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  
